"""I/O and OpenDSS file modification utilities."""

import json
import logging
import shutil
from pathlib import Path

from .schemas import LoadSpec, OrchestrationSummary

logger = logging.getLogger(__name__)


def prepare_output_directory(source_dir: Path, output_dir: Path) -> Path:
    """Copy source OpenDSS model files into target output directory.

    Args:
        source_dir: Path to original model directory.
        output_dir: Destination path for output model.

    Returns:
        Resolved output directory Path.
    """
    output_dir = output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    # Copy files from source to output
    for item in source_dir.iterdir():
        dest_item = output_dir / item.name
        if item.is_dir():
            if dest_item.exists():
                shutil.rmtree(dest_item)
            shutil.copytree(item, dest_item)
        elif item.is_file():
            shutil.copy2(item, dest_item)

    logger.info("Copied OpenDSS model from '%s' to '%s'", source_dir, output_dir)
    return output_dir


def write_load_definitions(
    dss_file_path: Path,
    bus_id: str,
    phases: list[int],
    load_spec: LoadSpec,
) -> Path:
    """Generate and write OpenDSS Load definition commands to a DSS file.

    Args:
        dss_file_path: Destination path for the new DSS file.
        bus_id: Target bus identifier.
        phases: List of phases connected.
        load_spec: Load specification.

    Returns:
        Path to the written DSS file.
    """
    dss_file_path = dss_file_path.resolve()
    num_phases = len(phases) if phases else 1
    kw_per_phase = load_spec.kw_total / num_phases
    kvar_per_phase = load_spec.kvar_total / num_phases

    lines: list[str] = [
        "! OpenDSS load definitions generated by pnnl-load-orchestration",
        f"! Allocated to Bus {bus_id} across phases {phases}",
    ]

    for ph in phases:
        load_name = f"{load_spec.load_name_prefix}_{bus_id}_ph{ph}"
        line = (
            f"New Load.{load_name} Bus1={bus_id}.{ph} Phases=1 "
            f"Conn={load_spec.conn} Model={load_spec.model_type} "
            f"kV={load_spec.kv_base} kW={kw_per_phase:.4f} kvar={kvar_per_phase:.4f}"
        )
        lines.append(line)

    lines.append("")  # Trailing newline

    with open(dss_file_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    logger.info("Wrote allocated load DSS file: %s", dss_file_path)
    return dss_file_path


def append_load_to_master(master_path: Path, load_dss_filename: str) -> None:
    """Append a Redirect command to the master DSS file.

    Args:
        master_path: Path to the master.dss file.
        load_dss_filename: Name or relative path of the load DSS file to redirect.
    """
    master_path = master_path.resolve()
    content = master_path.read_text(encoding="utf-8")
    redirect_cmd = f"Redirect {load_dss_filename}"

    if redirect_cmd in content:
        logger.debug("Redirect command already present in %s", master_path)
        return

    # Insert redirect before CalcVoltageBases if present, otherwise append at end
    if "CalcVoltageBases" in content:
        modified_content = content.replace("CalcVoltageBases", f"{redirect_cmd}\nCalcVoltageBases", 1)
    elif "calcvoltagebases" in content:
        modified_content = content.replace("calcvoltagebases", f"{redirect_cmd}\ncalcvoltagebases", 1)
    else:
        modified_content = f"{content.rstrip()}\n\n! Added by pnnl-load-orchestration\n{redirect_cmd}\n"

    master_path.write_text(modified_content, encoding="utf-8")
    logger.info("Added '%s' to master file '%s'", redirect_cmd, master_path)


def save_summary(output_path: Path, summary: OrchestrationSummary) -> Path:
    """Save OrchestrationSummary to a JSON file.

    Args:
        output_path: Destination JSON file path.
        summary: OrchestrationSummary instance.

    Returns:
        Path to saved JSON file.
    """
    output_path = output_path.resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    json_data = json.loads(summary.model_dump_json())

    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(json_data, f, indent=2)

    logger.info("Saved orchestration summary: %s", output_path)
    return output_path
